version: '3.8'

services:

  postgres:
    image: postgres:15-alpine
    container_name: aerostic-postgres
    restart: always
    environment:
      POSTGRES_USER: aerostic
      POSTGRES_PASSWORD: strongpassword
      POSTGRES_DB: aerostic
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          memory: 4g

  nginx:
    image: nginx:alpine
    container_name: aerostic-nginx
    restart: always
    network_mode: host
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../nginx/ssl:/etc/nginx/ssl:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      # Static Assets Mounts
      - /var/www/aerostic/frontend/landing/dist:/usr/share/nginx/html/landing:ro
      - /var/www/aerostic/frontend/app-dashboard/.next/static:/usr/share/nginx/html/app/_next/static:ro
      - /var/www/aerostic/frontend/app-dashboard/public:/usr/share/nginx/html/app/public:ro

  redis:
    image: redis:7-alpine
    container_name: aerostic-redis
    restart: always
    command: redis-server --maxmemory 1gb --maxmemory-policy noeviction
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: aerostic-zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: aerostic-kafka
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  ml-service:
    build:
      context: ../../
      dockerfile: ml-service/Dockerfile
    container_name: aerostic-ml
    restart: always
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

volumes:
  postgres_data:
  redis_data:
